### ISSUE TITLE
A lot of time spent in `do_at_generic_first_appt_non_emergency` due to repeated dataframe access

### ISSUE THREAD

**Issue by matt-graham** [UCL/TLOmodel#1237]
In the [latest scheduled profiling run](http://github-pages.ucl.ac.uk/TLOmodel-profiling/_static/profiling_html/schedule_254_7984913f075d8f96a670bc70b54cb21319f35e58.html), 21.4% of the overall run time was spent in calls to `do_at_generic_first_appt_non_emergency`. Looking at the breakdown of time spent inside the function, most of the time is spent in evauating `_LocIndexer.__getitem__` (that is performing `loc` indexing operations on the population dataframe), both directly and as part of `SymptomManager.has_what` calls. 

My understanding of this function is that it acts as an initial trigger for the scheduling of specific HSI events connected with different disease modules, but beyond scheduling further HSI events, should not immediately make any changes to the properties of the individual with the associated `person_id` ? @tbhallett can I check this is correct.

If this is the case, then we can avoid the repeated dataframe access by doing a single initial read of the individuals properties at the beginning of the function and then passing a datastructure containing these values to all called functions. Ideally we would make this datastructure immutable - for example created a `namedtuple` to be explicit that the properties are read only and cannot be updated. Given a lot of the dataframe accesses are part of `SymptomManager.has_what` calls, we would need to refactor this / provide an alternative method to allowing passing the properties directly (as for example a named tuple), and potentially also evaluate the symptoms the individual has once and pass in explicitly to called functions to avoid overhead in reconstructing the symptom list multiple times.

If we do require allowing direct updates to individual properties as part of these calls, and alternative to using an immutable data structure, would be to create a class which will allows changing property values, but records which property are changed and writes these back to the population dataframe at the end of the call.

A possibly nice way to do all of this and also simplify the structure of `do_at_generic_first_appt_non_emergency` (and analagously `do_at_generic_first_appt_emergency`) would be to add methods (defaulting to a no-op) to the base `Module` class which deal with scheduling the necessary follow-on HSI events  from a generic first [non-emergency | emergency] appointment for each disease module, something like

```Python

class Module:
    
    ...

    def do_at_generic_first_appt_non_emergency(self, person_id: int, person_properties: namedtuple, symptoms: list[str]):
        """Schedule any HSI events following on from a non-emergency generic first appointment."""
        ...


    def do_at_generic_first_appt_emergency(self, person_id: int, person_properties: namedtuple, symptoms: list[str]):
        """Schedule any HSI events following on from an emergency generic first appointment."""
        ...
```

with corresponding functions in `hsi_generic_first_appts` module

```Python
def do_at_generic_first_appt_non_emergency(hsi_event, squeeze_factor):
    person_id = hsi_event.target
    person_properties = hsi_event.sim.population.get_individual_properties(person_id)
    symptoms = hsi_event.sim.modules['SymptomManager'].has_what_from_properties(person_properties )
    for module in hsi_event.sim.modules.values():
        module.do_at_generic_first_appt_non_emergency(person_id, person_properties, symptoms)

def do_at_generic_first_appt_emergency(hsi_event, squeeze_factor):
    person_id = hsi_event.target
    person_properties = hsi_event.sim.population.get_individual_properties(person_id)
    symptoms = hsi_event.sim.modules['SymptomManager'].has_what_from_properties(person_properties )
    for module in hsi_event.sim.modules.values():
        module.do_at_generic_first_appt_emergency(person_id, person_properties, symptoms)
```

which avoids the large number of `if` statements and module specific logic in the current implementation. Given it's passed to these function we could also pass through `squeeze_factor` to the modules methods if its thought this will be used at some point in future.

My main concern with this approach would be the difficulty in enforcing the condition that modules `do_at_generic_first_appt_non_emergency` and `do_at_generic_first_appt_emergency` only schedule HSI events and do not edit properties of the individual directly (which would invalidate the approach of reading the properties once at beginning of method). We could just rely on documenting this expectation and adding tests to check it is adhered to. 

Alternatively at the cost of more complex function signatures, we could make `do_at_generic_first_appt_non_emergency` and `do_at_generic_first_appt_emergency` static methods of the modules, without direct access to the module attributes (including the population data frame). In this case we would need to pass through all objects that would be needed for dealing with scheduling following on HSI events as arguments.

**Comment by tbhallett** [comment]
> My understanding of this function is that it acts as an initial trigger for the scheduling of specific HSI events connected with different disease modules, but beyond scheduling further HSI events, should not immediately make any changes to the properties of the individual with the associated `person_id` ? @tbhallett can I check this is correct.

100% correct

**Comment by tbhallett** [comment]
This sounds excellent! :-)

**Comment by tamuri** [comment]
SymptomManager does have a `have_what(person_ids)` method which could be used to efficiently get all the symptoms for persons. It's using `apply` right now but can probably be made more efficient using native operations on the dataframe (maybe, flatten the symptom columns for persons of interest, change to True/False indicating >0, then collect into list...?)

**Comment by willGraham01** [comment]
It sounds like there are 2 separate things we want to tackle here: changes to get us the performance improvements, and a refactoring to make codebase more readable and shift towards implementing module-specific behaviour within the modules themselves.

## 1: Make initial changes to (hopefully) provide performance speed-up.

- At the start of `do_at_generic_first_appt_non_emergency`, run calls to the population dataframe, symptom list, etc once and store the results (preferably in an immutable data type).
- For each of the modules, refactor the particular methods that are called in `do_at_generic_first_appt_non_emergency` so that they take in these top-level data-structures as parameters rather than reconstructing them when they run.

This should let us enjoy the performance speed-up that's on offer in the initial issue (less time in dataframe accesses and constructing the symptom list).

It should _also_ flag up to us any instances where a module _is_ making changes to the population dataframe.
If we initially try to use immutable data structures and start hitting errors, we can flag this up with whoever is in charge of the module (and potentially review if a more flexible data type would be appropriate).

Finally, it also sets the stage for the refactor below.

## 2: Refactor the module methods that are called in `do_at_generic_first_appt_non_emergency`

- Decide on a common function signature for all the module-methods that are called in `do_at_generic_first_appt_non_emergency`.
- Add generic method to the `Module` class that defaults to not-implemented error.
- Refactor existing modules to overwrite this method - this will also standardise the naming convention for these methods.
- Rewrite the `do_at_generic_first_appt_non_emergency` to use a for loop as in Matt's suggestion above.
- If we can use immutable data-types; make the module methods static class methods.

This refactor might run into problems since we currently have an additional layer of logic determining which symptoms are checked, based on the patient's age. Some of this functionality might need to be refactored _into_ the module methods themselves.
Theoretically this change is just a readability improvement, so we should preserve the speed-up gains from before.

**Comment by willGraham01** [comment]
Hi all - in light of Matt's suggestions for reorganising and speeding up how the `do_at_generic_first_appt_non_emergency` function (and classes that are involved), I've opened #1289 which provides some typehints and a slight refactoring to hopefully make development on this issue slightly easier.

It doesn't change any functionality - just moves code around and tidies up some of the internal logic (removing redundant checks, standardising how properties are used, minimising how many things we actually need to store in the class, etc). And it means that PyCharm / VSCode etc should be able to provide syntax-highlighting for class methods and completion suggestions if typehints are enabled.

**Comment by willGraham01** [comment]
Raising https://github.com/UCL/TLOmodel/issues/407 here which we're also addressing in this issue
