### ISSUE TITLE
Investigate whether / how model behaviour is affected by ordering of modules in HSI generic first appointments

### ISSUE THREAD

**Issue by matt-graham** [UCL/TLOmodel#1383]
Our investigations in #1348 and #1366 suggest the ordering in which modules are looped over in 

https://github.com/UCL/TLOmodel/blob/df25c764e6d6fc99f224a65d18a030c67630c5a4/src/tlo/methods/hsi_generic_first_appts.py#L66-L103

may be leading to significant differences in the model behaviour beyond the expected statistical variations due to differing random values being generated. Once the inconsistences discussed in #1348 are fixed we should check if we still see this behaviour and if so investigate why it is arising.

**Comment by marghe-molaro** [comment]
Recapping here how we think same-day appts scheduled from generic first appts should work in mode 2:
- Originally, mode 2 would (like in mode 1) collect all appts due on the day, run them, and then query the queue again to check whether any more appts for the same day had been scheduled;
- This clashed with a rigorous enforcement of prioritisation in the queue in what we referred to as "mid-day effects", as follows: if a higher priority appointment had been scheduled for the same by one of the generic first appts initially collected, it would have been put back in the generic HSI queue and hence only dealt with after all other (potentially lower priority) initially-collected HSI events had ran. In a resource-constraint context, this would have given the higher priority appt a lower probability of running, which is incorrect.
- To fix this, we therefore modified how mode 2 works such that instead of collecting all events due on the day in the queue before running them, it queries the events one by one and runs them immediately. In doing so, if a new HSI event is added for the same day in the HSI events queue, its priority - as well as the date on which it is due - will determine how soon that HSI can be ran. 
-

**Comment by marghe-molaro** [comment]
From some quick tests, the behaviour of mode 2 for same-day events appears to be as expected:
- Priority in querying same-day events is respected;
- If, when running an HSI event, this schedules a follow-up appt for that person on the same day, that new HSI is queried and ran on the same day;
- The position of the new same-day event appears to be in the middle of generic_first_appts for other individuals (which, given that I'm looking at the first day in the simulation, would have had to be scheduled before that follow-up event) suggesting that the order of the follow-up event is not determined by when the event was added to the queue (i.e. its location in the queue is random for equal priority and date)

**Comment by matt-graham** [comment]
From @marghe-molaro's investigations detailed in https://github.com/UCL/TLOmodel/issues/1348#issuecomment-2151577781 it seems that module order in HSI generic first appointments logic does __not__ have a significant effect on module behaviour, which is as expected, so closing this.
